import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { analyzeMeeting, analyzeMeetingAndCreateTasks, detectRisks, generateAnnouncement, getEvents } from '../services/api';

const Result = ({children}) => <div className="mt-4 p-4 rounded-xl bg-surface-container text-on-surface text-sm whitespace-pre-wrap overflow-auto max-h-[420px]">{children}</div>;

export default function AIAssistant(){
 const [params]=useSearchParams(); const [activeTab,setActiveTab]=useState(params.get('tab')||'meetings'); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [events,setEvents]=useState([]); const [eventId,setEventId]=useState('');
 const [notes,setNotes]=useState(params.get('notes')||''); const [meetingResult,setMeetingResult]=useState(null); const [riskInfo,setRiskInfo]=useState(''); const [riskResult,setRiskResult]=useState(null); const [announcementInfo,setAnnouncementInfo]=useState(''); const [announcementResult,setAnnouncementResult]=useState(null);
 useEffect(()=>{const tab=params.get('tab'); if(tab&&['meetings','risks','announcements'].includes(tab))setActiveTab(tab); if(params.get('notes'))setNotes(params.get('notes'));},[params]);
 useEffect(()=>{getEvents().then(d=>{const e=Array.isArray(d)?d:d?.events||[];setEvents(e);if(e[0])setEventId(String(e[0].id));}).catch(()=>{});},[]);
 const run=async(fn)=>{setLoading(true);setError('');try{await fn();}catch(e){setError(e.message||'AI request failed');}finally{setLoading(false);}};
 const analyze=()=>run(async()=>setMeetingResult(await analyzeMeeting(notes)));
 const createTasks=()=>{if(!eventId){setError('Select an event before creating tasks.');return;}return run(async()=>setMeetingResult(await analyzeMeetingAndCreateTasks(eventId,notes)));};
 const risks=()=>run(async()=>setRiskResult(await detectRisks(riskInfo)));
 const announcement=()=>run(async()=>setAnnouncementResult(await generateAnnouncement(announcementInfo)));
 const renderMeeting=()=> <div className="grid lg:grid-cols-2 gap-space-lg"><section className="p-space-lg rounded-2xl bg-surface-container-lowest shadow-sm border border-outline-variant/30"><h2 className="font-title-lg font-semibold">Paste Meeting Notes</h2><p className="text-sm text-on-surface-variant mb-4">Unstructured raw input</p><select value={eventId} onChange={e=>setEventId(e.target.value)} className="w-full mb-3 rounded-xl border border-outline-variant p-3 bg-surface-container-low"><option value="">Select event for task creation</option>{events.map(e=><option key={e.id} value={e.id}>{e.name||e.title}</option>)}</select><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Paste raw executive minutes here..." className="w-full min-h-56 rounded-xl border border-outline-variant bg-surface-container-low p-4 outline-none focus:ring-2 focus:ring-primary/20"/><div className="flex gap-2 mt-3"><button disabled={loading||!notes.trim()} onClick={analyze} className="flex-1 py-3 rounded-xl bg-primary text-on-primary disabled:opacity-50">{loading?'Analyzing...':'Analyze Meeting'}</button><button disabled={loading||!notes.trim()||!eventId} onClick={createTasks} className="flex-1 py-3 rounded-xl bg-secondary text-on-secondary disabled:opacity-50">{loading?'Working...':'Analyze & Create Tasks'}</button></div></section><section className="p-space-lg rounded-2xl bg-surface-container-lowest shadow-sm border border-outline-variant/30"><h2 className="font-title-lg font-semibold">Intelligence Output</h2>{error&&<div className="mt-3 p-3 rounded-lg bg-error-container text-on-error-container">{error}</div>}{meetingResult?<Result>{JSON.stringify(meetingResult,null,2)}</Result>:<div className="mt-4 min-h-56 rounded-xl bg-surface-container-low flex items-center justify-center text-on-surface-variant">Run analysis to see results.</div>}</section></div>;
 const renderRisks=()=> <div className="grid lg:grid-cols-2 gap-space-lg"><section className="p-space-lg rounded-2xl bg-surface-container-lowest shadow-sm border border-outline-variant/30"><h2 className="font-title-lg font-semibold">Risk Detector & Mitigator</h2><textarea value={riskInfo} onChange={e=>setRiskInfo(e.target.value)} placeholder="Describe the event situation, blockers, dependencies or operational concerns..." className="w-full min-h-64 mt-4 rounded-xl border border-outline-variant bg-surface-container-low p-4"/><button disabled={loading||!riskInfo.trim()} onClick={risks} className="w-full mt-3 py-3 rounded-xl bg-primary text-on-primary disabled:opacity-50">{loading?'Detecting...':'Detect Risks'}</button></section><section className="p-space-lg rounded-2xl bg-surface-container-lowest shadow-sm border border-outline-variant/30"><h2 className="font-title-lg font-semibold">Risk Intelligence</h2>{riskResult?<Result>{JSON.stringify(riskResult,null,2)}</Result>:<div className="mt-4 min-h-64 rounded-xl bg-surface-container-low flex items-center justify-center text-on-surface-variant">Run risk detection to see results.</div>}</section></div>;
 const renderAnnouncements=()=> <div className="grid lg:grid-cols-2 gap-space-lg"><section className="p-space-lg rounded-2xl bg-surface-container-lowest shadow-sm border border-outline-variant/30"><h2 className="font-title-lg font-semibold">Announcement Generator</h2><textarea value={announcementInfo} onChange={e=>setAnnouncementInfo(e.target.value)} placeholder="Describe the event, audience, purpose and important information..." className="w-full min-h-64 mt-4 rounded-xl border border-outline-variant bg-surface-container-low p-4"/><button disabled={loading||!announcementInfo.trim()} onClick={announcement} className="w-full mt-3 py-3 rounded-xl bg-primary text-on-primary disabled:opacity-50">{loading?'Generating...':'Generate Announcement'}</button></section><section className="p-space-lg rounded-2xl bg-surface-container-lowest shadow-sm border border-outline-variant/30"><h2 className="font-title-lg font-semibold">Announcement Output</h2>{announcementResult?<Result>{JSON.stringify(announcementResult,null,2)}</Result>:<div className="mt-4 min-h-64 rounded-xl bg-surface-container-low flex items-center justify-center text-on-surface-variant">Generate an announcement to see results.</div>}</section></div>;
 return <main className="w-full flex flex-col p-6 space-y-6 bg-background min-h-screen"><div><div className="flex items-center gap-2"><span className="px-2 py-0.5 rounded-full bg-secondary-fixed text-on-secondary-fixed font-label-sm font-semibold">✦ Intelligence Studio</span><span className="text-outline font-mono text-xs">v2.4-neural-engine</span></div><h1 className="font-headline-xl text-headline-xl text-on-surface tracking-tight mt-2">ClubOps AI Copilot & Operations Intelligence</h1><p className="text-on-surface-variant max-w-3xl">Turn meeting notes, event information and communication needs into structured operational outputs.</p></div><div className="flex items-center p-1 rounded-xl bg-surface-container gap-1 shadow-sm w-fit"><button onClick={()=>setActiveTab('meetings')} className={`px-4 py-2 rounded-lg font-semibold ${activeTab==='meetings'?'bg-surface-container-lowest text-primary shadow-sm':''}`}>1. Meeting Analyzer</button><button onClick={()=>setActiveTab('risks')} className={`px-4 py-2 rounded-lg font-semibold ${activeTab==='risks'?'bg-surface-container-lowest text-primary shadow-sm':''}`}>2. Risk Detector & Mitigator</button><button onClick={()=>setActiveTab('announcements')} className={`px-4 py-2 rounded-lg font-semibold ${activeTab==='announcements'?'bg-surface-container-lowest text-primary shadow-sm':''}`}>3. Copy & Announcement Studio</button></div>{activeTab==='meetings'?renderMeeting():activeTab==='risks'?renderRisks():renderAnnouncements()}</main>;
}
