import { useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import Modal from '../components/Modal';

const seed=[
{id:1,title:'Welcome to Club Orientation 2026',preview:'Welcome everyone! We are so excited to kick off another year of innovation...',audience:'First-year Students',status:'Published',date:'Sep 15, 2026'},
{id:2,title:'HackQuest Volunteer Briefing',preview:'All assigned volunteers for HackQuest must attend the mandatory briefing...',audience:'Volunteers',status:'Scheduled',date:'Sep 22, 2026'},
{id:3,title:'Venue Update',preview:'The main auditorium is currently undergoing maintenance, so we are moving to...',audience:'Core Team',status:'Draft',date:'Pending'},
];

export default function Announcements(){
 const navigate=useNavigate(); const [params]=useSearchParams(); const [items,setItems]=useState(seed); const [modal,setModal]=useState(params.get('action')==='new'?'edit':null); const [selected,setSelected]=useState(null); const [form,setForm]=useState({title:'',audience:'All Members',message:'',status:'Draft',date:'Pending'});
 const openNew=()=>{setSelected(null);setForm({title:'',audience:'All Members',message:'',status:'Draft',date:'Pending'});setModal('edit');};
 const openEdit=a=>{setSelected(a);setForm({title:a.title,audience:a.audience,message:a.preview,status:a.status,date:a.date});setModal('edit');};
 const save=e=>{e.preventDefault();if(!form.title.trim())return;const item={id:selected?.id||Date.now(),title:form.title,audience:form.audience,preview:form.message,date:form.date||'Pending',status:form.status};setItems(xs=>selected?xs.map(x=>x.id===selected.id?item:x):[item,...xs]);setModal(null);};
 return <div className="flex flex-col gap-space-lg w-full max-w-5xl mx-auto pb-space-xl"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-space-md"><div><h1 className="font-headline-lg text-headline-lg text-on-surface tracking-tight">Announcements</h1><p className="font-body-md text-on-surface-variant mt-1">Create, review and distribute club communications.</p></div><div className="flex gap-2"><button onClick={()=>navigate('/ai?tab=announcements')} className="flex items-center gap-2 px-space-md py-2 rounded-xl bg-secondary-fixed text-on-secondary-fixed shadow-sm"><span className="material-symbols-outlined text-[18px]">auto_awesome</span>Generate with AI</button><button onClick={openNew} className="flex items-center gap-2 px-space-md py-2 rounded-xl bg-primary text-on-primary shadow-sm"><span className="material-symbols-outlined">add</span>New Announcement</button></div></div>
 <div className="grid grid-cols-2 lg:grid-cols-4 gap-space-md">{[['Published',items.filter(x=>x.status==='Published').length],['Drafts',items.filter(x=>x.status==='Draft').length],['Scheduled',items.filter(x=>x.status==='Scheduled').length],['Total',items.length]].map(([l,v],i)=><div key={l} className={`p-space-md rounded-xl shadow-sm border border-outline-variant/30 flex flex-col items-center justify-center text-center ${i===0?'bg-primary text-on-primary':'bg-surface-container-lowest'}`}><div className="font-headline-lg font-bold">{v}</div><div className="font-title-sm font-semibold mt-1">{l}</div></div>)}</div>
 <div className="flex flex-col gap-space-sm"><h2 className="font-title-lg text-title-lg text-on-surface font-semibold">Recent Announcements</h2>{items.map(a=><div key={a.id} className="p-space-md rounded-xl bg-surface-container-lowest shadow-sm border border-outline-variant/30"><div className="flex items-center justify-between"><span className={`px-2.5 py-0.5 rounded-full text-sm ${a.status==='Published'?'bg-primary-container text-on-primary-container':a.status==='Scheduled'?'bg-secondary-container text-on-secondary-container':'bg-surface-container text-on-surface-variant'}`}>{a.status}</span><span className="text-sm text-on-surface-variant">{a.date}</span></div><h3 className="font-title-md text-on-surface font-semibold mt-3">{a.title}</h3><p className="text-sm text-on-surface-variant mt-1">"{a.preview}"</p><div className="flex items-center justify-between mt-4 pt-3 border-t border-outline-variant/20"><span className="px-2 py-1 rounded bg-surface-container-low text-sm">Audience: {a.audience}</span><div className="flex gap-2"><button onClick={()=>{setSelected(a);setModal('preview')}} className="px-3 py-1.5 rounded-lg border border-outline text-on-surface">Preview</button><button onClick={()=>openEdit(a)} className="px-3 py-1.5 rounded-lg bg-surface-container-low text-on-surface flex items-center gap-1"><span className="material-symbols-outlined text-[16px]">edit</span>Edit</button></div></div></div>)}</div>
 <Modal open={modal==='edit'} title={selected?'Edit Announcement':'New Announcement'} onClose={()=>setModal(null)} footer={<><button onClick={()=>setModal(null)} className="px-4 py-2 rounded-lg bg-surface-container">Cancel</button><button form="announcement-form" className="px-4 py-2 rounded-lg bg-primary text-on-primary">Save Draft</button></>}><form id="announcement-form" onSubmit={save} className="space-y-3"><label className="block text-sm font-medium">Subject *<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="mt-1 w-full rounded-lg border border-outline-variant p-2.5"/></label><label className="block text-sm font-medium">Audience<select value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})} className="mt-1 w-full rounded-lg border border-outline-variant p-2.5"><option>All Members</option><option>Volunteers</option><option>Core Team</option><option>Participants</option></select></label><label className="block text-sm font-medium">Message<textarea required value={form.message} onChange={e=>setForm({...form,message:e.target.value})} rows="6" className="mt-1 w-full rounded-lg border border-outline-variant p-2.5"/></label></form></Modal>
 <Modal open={modal==='preview'} title="Announcement Preview" onClose={()=>setModal(null)} footer={<button onClick={()=>setModal(null)} className="px-4 py-2 rounded-lg bg-primary text-on-primary">Close</button>}><div className="space-y-3"><span className="text-sm text-on-surface-variant">Audience: {selected?.audience}</span><h3 className="text-xl font-semibold">{selected?.title}</h3><p className="whitespace-pre-wrap text-on-surface-variant">{selected?.preview}</p></div></Modal>
 </div>
}
