import { useEffect, useState } from 'react';
import Modal from '../components/Modal';
import { createVolunteer, deleteVolunteer, getEvents, getVolunteers, updateVolunteer } from '../services/api';

const seed = [
 {id:1,name:'Ananya Sharma',role:'Logistics Lead',email:'ananya@example.com',phone:'',event:'HackQuest 2026',event_id:1,status:'Available'},
 {id:2,name:'Dev Patel',role:'Technical Lead',email:'dev@example.com',phone:'',event:'HackQuest 2026',event_id:1,status:'On Shift'},
 {id:3,name:'Sneha Mehta',role:'Outreach',email:'sneha@example.com',phone:'',event:'HackQuest 2026',event_id:1,status:'Available'},
 {id:4,name:'Rohan Shah',role:'Design Lead',email:'rohan@example.com',phone:'',event:'HackQuest 2026',event_id:1,status:'Assigned'},
];

export default function Volunteers(){
 const [volunteers,setVolunteers]=useState(seed); const [events,setEvents]=useState([]); const [modal,setModal]=useState(null); const [selected,setSelected]=useState(null); const [form,setForm]=useState({name:'',email:'',phone:'',role:'',skills:'',availability:'Available',event_id:'',notes:''}); const [busy,setBusy]=useState(false);
 useEffect(()=>{getEvents().then(d=>setEvents(Array.isArray(d)?d:d?.events||[])).catch(()=>{});},[]);
 const loadEvent=async(id)=>{if(!id)return; try{const d=await getVolunteers(id); if(Array.isArray(d))setVolunteers(d); else if(d?.volunteers)setVolunteers(d.volunteers);}catch{}};
 const openAdd=()=>{setSelected(null);setForm({name:'',email:'',phone:'',role:'',skills:'',availability:'Available',event_id:events[0]?.id||1,notes:''});setModal('form');};
 const openEdit=v=>{setSelected(v);setForm({name:v.name||v.full_name||'',email:v.email||'',phone:v.phone||'',role:v.role||'',skills:v.skills||'',availability:v.availability||v.status||'Available',event_id:v.event_id||events[0]?.id||1,notes:v.notes||''});setModal('form');};
 const save=async(e)=>{e.preventDefault(); if(!form.name.trim()||!form.event_id)return;setBusy(true);try{const payload={name:form.name,email:form.email,phone:form.phone,role:form.role,skills:form.skills,availability:form.availability,notes:form.notes};if(selected){const d=await updateVolunteer(selected.id,payload);setVolunteers(vs=>vs.map(v=>v.id===selected.id?{...v,...form,...(d||{})}:v));}else{const d=await createVolunteer(form.event_id,payload);setVolunteers(vs=>[{id:d?.id||Date.now(),...form,...(d||{})},...vs]);}setModal(null);}catch(err){alert(err.message);}finally{setBusy(false);}};
 const remove=async(v)=>{if(!confirm(`Delete ${v.name}?`))return;try{await deleteVolunteer(v.id);setVolunteers(vs=>vs.filter(x=>x.id!==v.id));}catch(err){alert(err.message);}};
 return <div className="flex flex-col gap-space-lg w-full max-w-6xl mx-auto pb-space-xl"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-space-md"><div><h1 className="font-headline-lg text-headline-lg text-on-surface tracking-tight">Volunteer Operations</h1><p className="font-body-md text-on-surface-variant mt-1">Manage event staffing and volunteer assignments.</p></div><button onClick={openAdd} className="flex items-center gap-2 px-space-md py-2 rounded-xl bg-primary text-on-primary font-label-md shadow-sm"><span className="material-symbols-outlined text-[18px]">person_add</span>Add Volunteer</button></div>
 <div className="grid grid-cols-2 md:grid-cols-4 gap-space-md">{[[volunteers.length,'Active Volunteers'],[volunteers.filter(v=>v.status==='Assigned'||v.status==='On Shift').length,'Assigned'],[volunteers.filter(v=>v.status==='Available').length,'Available'],['94%','Coverage']].map(([v,l],i)=><div key={l} className={`p-space-md rounded-xl shadow-sm border border-outline-variant/30 flex flex-col items-center justify-center text-center ${i===3?'bg-primary-container text-on-primary-container':'bg-surface-container-lowest'}`}><div className="font-headline-lg font-bold">{v}</div><div className="font-title-sm font-semibold mt-1">{l}</div></div>)}</div>
 <div className="p-space-md rounded-2xl bg-surface-container-lowest shadow-sm border border-outline-variant/30"><h2 className="font-title-lg text-on-surface font-semibold mb-4">Volunteer Roster</h2><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left"><thead><tr className="border-b border-outline-variant/30 text-on-surface-variant text-sm"><th className="pb-3 px-2">Volunteer</th><th>Role</th><th>Email</th><th>Event</th><th>Status</th><th className="text-right">Actions</th></tr></thead><tbody>{volunteers.map(v=><tr key={v.id} className="border-b border-outline-variant/10"><td className="py-3 px-2"><div className="flex items-center gap-3"><div className="w-8 h-8 rounded-full bg-secondary text-on-secondary flex items-center justify-center font-semibold">{(v.name||'?').split(' ').map(n=>n[0]).join('').slice(0,2)}</div>{v.name}</div></td><td>{v.role}</td><td>{v.email}</td><td>{v.event||v.event_name||'Event'}</td><td><span className="px-2 py-0.5 rounded-full bg-surface-container text-on-surface-variant text-xs">{v.status||v.availability||'Available'}</span></td><td className="text-right"><div className="flex justify-end gap-2"><button onClick={()=>openEdit(v)} className="text-primary text-sm">Edit</button><button onClick={()=>remove(v)} className="text-error text-sm">Delete</button></div></td></tr>)}</tbody></table></div></div>
 <Modal open={modal==='form'} title={selected?'Edit Volunteer':'Add Volunteer'} onClose={()=>setModal(null)} footer={<><button onClick={()=>setModal(null)} className="px-4 py-2 rounded-lg bg-surface-container">Cancel</button><button form="volunteer-form" disabled={busy} className="px-4 py-2 rounded-lg bg-primary text-on-primary">{busy?'Saving...':'Save'}</button></>}><form id="volunteer-form" onSubmit={save} className="space-y-3"><label className="block text-sm font-medium">Full Name *<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-1 w-full rounded-lg border border-outline-variant p-2.5"/></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Email<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="mt-1 w-full rounded-lg border border-outline-variant p-2.5"/></label><label className="text-sm font-medium">Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="mt-1 w-full rounded-lg border border-outline-variant p-2.5"/></label></div><label className="block text-sm font-medium">Event<select required value={form.event_id} onChange={e=>setForm({...form,event_id:e.target.value})} className="mt-1 w-full rounded-lg border border-outline-variant p-2.5"><option value="">Select event</option>{events.map(ev=><option key={ev.id} value={ev.id}>{ev.name||ev.title}</option>)}{events.length===0&&<option value="1">HackQuest 2026</option>}</select></label><label className="block text-sm font-medium">Role<input value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="mt-1 w-full rounded-lg border border-outline-variant p-2.5"/></label><label className="block text-sm font-medium">Skills<input value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})} className="mt-1 w-full rounded-lg border border-outline-variant p-2.5"/></label><label className="block text-sm font-medium">Availability<select value={form.availability} onChange={e=>setForm({...form,availability:e.target.value})} className="mt-1 w-full rounded-lg border border-outline-variant p-2.5"><option>Available</option><option>Assigned</option><option>Unavailable</option></select></label><label className="block text-sm font-medium">Notes<textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} rows="3" className="mt-1 w-full rounded-lg border border-outline-variant p-2.5"/></label></form></Modal>
 </div>
}
